### ISSUE TITLE
Error while running setup.py

### ISSUE THREAD

**Issue by affer** [Fr00t/easee2mqtt#1]
got this error at the bottom:  (ive changed the serial number of my charger to xxx and also the email, i get the same error when i try with a hostname! using python 3.8. hope it is an easy fix.. thanks

affer@raspberrypi:~/easee/easee2mqtt $ python setup.py
/home/affer/easee/easee2mqtt/easeelog.log
/home/affer/easee/easee2mqtt/easeelog.log
Running setup of Easee2MQTT.

Please input e-mail of Easee account: xxx@xxx.com
Please input password of Easee account: 
Successfully connected to Easee!
The following chargers has been found on this account. Note that the charger ID shown here will make up the MQTT-topic.
If you get a new charger, please re-run settings.
XXXXXXXX
Please input IP or adress of MQTT-broker: 192.168.1.200
Input MQTT-port, default=1883: 
Input MQTT-username, leave blank if no authentication is required: 
Please wait, testing connection...
Successfully connected to MQTT-broker
Available QOS-levels of MQTT: 
0 - At most once
1 - At least once
2 - Exactly once
Input QOS-level, recommended 1: 
Traceback (most recent call last):
  File "setup.py", line 134, in <module>
    settings['mqtt_adress'] = int(mqtt_adress)
ValueError: invalid literal for int() with base 10: '192.168.1.200'

**Comment by affer** [comment]
edited line 134 to:
   settings['mqtt_adress'] = mqtt_adress
from
   settings['mqtt_adress'] =  int(mqtt_adress) 

now i could finish setup

**Comment by Fr00t** [comment]
Strange. I don't know why I would convert the IP to an int, makes no sense. I also don't understand why it's worked up until I just tested. 

Anyway fixed it now, thanks :)

https://github.com/Fr00t/easee2mqtt/commit/0bb8d02ce55712846d729020d864aa35eea19040
