### ISSUE TITLE
Error thrown if no chargers

### ISSUE THREAD

**Issue by svenove** [Fr00t/easee2mqtt#2]
Just installed and the charger isn’t mounted yet. 

Running python setup.py throws an exception when no charger is found in the account. Would be better to throw an error message. 

“ Successfully connected to Easee!
Traceback (most recent call last):
  File "setup.py", line 88, in <module>
    chargers = get_chargers()
  File "setup.py", line 60, in get_chargers
    for circuit in parsed[0].get("circuits", []):
IndexError: list index out of range”

**Comment by Fr00t** [comment]
Hey @svenove,

I agree that should definitely cause an error instead of exception. I've commited a change to hopefully catch the exception now. Could you give it a go and report back? :)
