### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by EskildPa** [Fr00t/easee2mqtt#4]
Running 'python setup.py', but gets this error:

Please input password of Easee account:
Traceback (most recent call last):
  File "/srv/homeauto/easee2mqtt/setup.py", line 83, in <module>
    access_token, expiry = get_access_token(easee_username, easee_password)
TypeError: cannot unpack non-iterable bool object

easeelog.log;
[2024-06-01 20:15:40] INFO Starting setup.
[2024-06-01 20:16:27] WARNING Failed to connect to Easee. Response code: 405

Python 3.9.2
Using a simple password with letters and digits only

Any hints?

**Comment by christofferr** [comment]
Replace the URL on line 30 in easee2mqtt.py to "https://api.easee.com/api/accounts/login". I have created a pull request to fix this.

**Comment by EskildPa** [comment]
Changing the URL fixed the issue. Thank you so much, @christofferr
